swagger: "2.0"
info:
  description: "This is a simple NodeJS service which returns some information(followers, likes, etc...) about specified user of Instagram"
  version: "1.0.0"
  title: "Instagram getter"
host: "localhost:8080"
schemes:
- "http"
paths:
  /users/{username}:
    get:
      summary: "Get user by user name"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be fetched."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        500:
          description: "Internal server error"
definitions:
  User:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Full name of the user"
      description:
        type: "string"
        description: "Biography of the user"
      followers:
        type: "integer"
        description: "Followers number"
      following:
        type: "integer"
        description: "Following number"
      posts:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            url:
              type: string
              description: The url of posted image
